// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members, depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7rRjc1cwkywE6xBW80yVqW_Mzynvoewg',
    appId: '1:229182234343:web:4c63a8ec6a286d755b0c42',
    messagingSenderId: '229182234343',
    projectId: 'fals-9b639',
    authDomain: 'fals-9b639.firebaseapp.com',
    storageBucket: 'fals-9b639.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwUXiED7aa6cu9Mg6lxuwtTtEPTNFCzGg',
    appId: '1:229182234343:android:5c119a4c8c25e45c5b0c42',
    messagingSenderId: '229182234343',
    projectId: 'fals-9b639',
    storageBucket: 'fals-9b639.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-5KVmIUtaXWyUbgJD-iuJUHiQnQFadWQ',
    appId: '1:229182234343:ios:d5ca008e6e41c4ae5b0c42',
    messagingSenderId: '229182234343',
    projectId: 'fals-9b639',
    storageBucket: 'fals-9b639.appspot.com',
    iosClientId:
        '229182234343-c1bp8q1mu85kpgchpn6f5rpp1n0q4hfh.apps.googleusercontent.com',
    iosBundleId: 'com.example.falApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-5KVmIUtaXWyUbgJD-iuJUHiQnQFadWQ',
    appId: '1:229182234343:ios:d5ca008e6e41c4ae5b0c42',
    messagingSenderId: '229182234343',
    projectId: 'fals-9b639',
    storageBucket: 'fals-9b639.appspot.com',
    iosClientId:
        '229182234343-c1bp8q1mu85kpgchpn6f5rpp1n0q4hfh.apps.googleusercontent.com',
    iosBundleId: 'com.example.falApp',
  );
}
